# Generated by Django 3.1.7 on 2021-04-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Civil_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_profile', models.CharField(max_length=50)),
                ('job_discription', models.CharField(max_length=100)),
                ('job_requirements', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('no_of_vaccancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IT_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_profile', models.CharField(max_length=50)),
                ('job_discription', models.CharField(max_length=100)),
                ('job_requirements', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('no_of_vaccancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mech_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('job_profile', models.CharField(max_length=50)),
                ('job_discription', models.CharField(max_length=100)),
                ('job_requirements', models.CharField(max_length=100)),
                ('experience', models.FloatField()),
                ('package', models.FloatField()),
                ('no_of_vaccancy', models.IntegerField()),
            ],
        ),
    ]
