# Generated by Django 3.1.7 on 2021-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_jobsapplied'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('resume', models.FileField(blank=True, null=True, upload_to='pics')),
                ('education', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('phone_no', models.IntegerField(unique=True)),
            ],
        ),
    ]
